/**
 * Isolated LeoPips UI copy. English-only for Phase 1 preview.
 * Do not promise that stakes cannot be lost. Do not use real-money wording.
 */

import {
  LEOPIPS_BIG_WIN_PAYOUT,
  LEOPIPS_HOME_PREVIEW,
  LEOPIPS_REFERRAL_REWARD,
  LEOPIPS_TOP_REFERRAL_USD,
  formatLeoPipsAmount,
} from "./leopipsEconomy.js";

export const LEOPIPS_COPY = Object.freeze({
  brand: "LEODOMINO",
  currency: "LEOPIPS",
  chooseStake: "Choose how many LeoPips you want to stake",
  changeStyle: "CHANGE STYLE",
  chooseStyleAria: "Choose a style",
  closeStyleMenu: "Close style menu",
  players: "2 PLAYERS",
  potentialPot: "POTENTIAL POT",
  play: "PLAY",
  mostPopular: "MOST POPULAR",
  insufficient: "Not enough LeoPips to enter Find Match.",
  friendsNote: "You can still play with friends.",
  friendsAction: "Play with friends",
  fairPlayTitle: "FAIR PLAY",
  fairPlayBody: "Server-protected matches",
  winBigTitle: "WIN BIG",
  winBigBody: `Win up to ${LEOPIPS_BIG_WIN_PAYOUT} LeoPips`,
  playEarnTitle: "PLAY & EARN",
  playEarnBody: "Compete, win and grow",
  // Player-facing. Matches remain server-authoritative; do not promise stakes cannot be lost.
  rulesNote: "Every LeoPips match is fair, secure, and protected.",
  // Home-page copy only. Do not show on Choose Stake. Hosted Invite & Win is unchanged.
  referralTitle: "Referral Reward",
  referralAmount: `+${LEOPIPS_REFERRAL_REWARD} LeoPips`,
  referralHint: "Invite a genuinely new player. Earn after the referral qualifies.",
  referralInvite: "Invite Friends",
  topReferralTitle: "TOP REFERRAL",
  topReferralPrize: `$${LEOPIPS_TOP_REFERRAL_USD} US`,
  topReferralEyebrow: "Cash prize",
  topReferralBody: "Promotional cash prize. Separate from LeoPips.",
  homeAria: "LeoDomino home",
  homeTagline: "Play. Win. Connect.",
  wordmarkLeo: "LEO",
  wordmarkDomino: "DOMINO",
  statusAria: "Player status",
  xpLabel: "XP",
  xpProgress: `${formatLeoPipsAmount(LEOPIPS_HOME_PREVIEW.xp)} / ${formatLeoPipsAmount(LEOPIPS_HOME_PREVIEW.xpNext)}`,
  levelLabel: `LVL ${LEOPIPS_HOME_PREVIEW.level}`,
  yourProgress: "Your progress",
  seasonN: `SEASON ${LEOPIPS_HOME_PREVIEW.season}`,
  leagueProgress: "Seasonal competition",
  playLeague: "Play League",
  playVsLeoBest: "Play vs LeoBest",
  offlineVs: "Play offline against LeoBest AI",
  oneVsOne: "1 vs 1",
  playOnline: "Play Online",
  playOnlineSub: "Play real players online",
  findMatch: "Find Match",
  playFriend: "Play a Friend",
  friendSub: "Invite a friend to play",
  invite: "Invite",
  privateTable: "Private Table",
  privateTableSub: "Create a private table",
  create: "Create",
  liveChat: "Live Chat",
  challengeName: "LeoDomino Challenge",
  viewChallenge: "View Challenge",
  leoCoinsStore: "LeoCoins Store",
  storeLead: "Get LeoCoins, avatars, table themes and more!",
  shopNow: "Shop now",
  navHome: "Home",
  navLeague: "League",
  navPlay: "Play",
  navStore: "Store",
  navMenu: "Menu",
  previewNotice: "Preview only. Live Home is unchanged.",
  notifications: "Notifications",
  profile: "Profile",
  settings: "Settings",
  congratulations: "Congratulations!",
  bigWin: "BIG WIN",
  continue: "Continue",
  youWon: (payout) => `You won ${formatLeoPipsAmount(payout)} LeoPips`,
});
