/**
 * Compatibility barrel — spatial engine lives in DominoLayoutEngine.js.
 * Legacy BoardLayoutEngine import paths keep working.
 */
export {
  TILE_ASPECT,
  CHAIN_GAP,
  GAP,
  MARGIN,
  PADDING,
  BRIDGE_LEN,
  MIN_TILE_SCALE,
  MIN_SCALE,
  TURN_EVERY,
  CHAIN_GAP_PX,
  SEGMENT_TILES,
  SAFETY_MARGIN_PX,
  MIN_BOARD_ZOOM,
  MAX_GLOBAL_ZOOM,
  rotationForTravel,
  orientationForTravel,
  rotationForOrientation,
  footprintForTravel,
  tileFootprint,
  computePlayBounds,
  computeLayoutMetrics,
  computeStableFitScale,
  measureMinRowClearance,
  countTurns,
  measureVerticalBridges,
  calculateBoardLayout,
  layoutBoard,
  layoutSnakeFromCenter,
  layoutHeight,
  layoutWidth,
  collisionBox,
  reserveFor,
  SPINNER_RESERVE,
  CORNER_RESERVE,
  BRIDGE_RESERVE,
  MIN_SAFE_GAP_PX,
} from "./DominoLayoutEngine.js";
