export { default as BoardContainer } from "./BoardContainer.jsx";
/** @deprecated Prefer BoardContainer */
export { default as BoardRenderer } from "./BoardContainer.jsx";
export {
  calculateBoardLayout,
  layoutBoard,
  orientationForTravel,
  footprintForTravel,
  computeLayoutMetrics,
  computeStableFitScale,
  computePlayBounds,
  computeSafeFeltBounds,
  computeChainBounds,
  computeFitScale,
  measureMinRowClearance,
  measureVerticalBridges,
  countTurns,
  BRIDGE_LEN,
  GAP,
  CHAIN_GAP,
  TURN_EVERY,
  RUN_CEILING,
  packRunLimit,
  packFirstRunLimit,
  packLaterRunSearchLimit,
  packSpinnerArmLimit,
  parallelRunClearance,
  usesAmericanBoardLayout,
  SPINNER_MAIN_STRAIGHT,
  SPINNER_ARM_STRAIGHT,
  FIRST_FOLD_RIGHT,
  FIRST_FOLD_LEFT,
  MARGIN,
  SAFE_FELT_INSET,
  MIN_TILE_SCALE,
  MIN_SCALE,
  MIN_BOARD_SCALE,
  BOARD_TILE_HAND_FACTOR,
  BOARD_BASE_SHORT_MIN_PX,
  BOARD_BASE_SHORT_MAX_PX,
  LOCKED_BOARD_TILE_SHORT_PX,
  LOCKED_BOARD_TILE_LONG_PX,
  resolveBoardTileBase,
  CHAIN_GAP_PX,
  SEGMENT_TILES,
  SAFETY_MARGIN_PX,
  collisionBox,
  reserveFor,
  SPINNER_RESERVE,
  CORNER_RESERVE,
  BRIDGE_RESERVE,
  MIN_SAFE_GAP_PX,
} from "./DominoLayoutEngine.js";
export {
  HAND_EXCLUSION_GAP_PX,
  measureHandExclusionPx,
} from "./handExclusion.js";
export {
  isBoardDebugEnabled,
  setBoardDebug,
  logCollision,
  edgeClearance,
  buildLayoutDebugInfo,
} from "./boardDebug.js";
export {
  assertLogicalConnections,
  assertVisualConnections,
  resolveTileDisplay,
  facingToward,
  facingHalf,
  pipOnHalf,
  buildBoardDisplays,
  buildSpinnerArmDisplays,
  layoutSpinnerArmPositions,
  exposedPipFromDisplay,
  validateBoardPresentation,
  reportBoardPresentation,
} from "./connectionDisplay.js";
export {
  playedTableTiles,
  layoutRenderedBoxes,
  inspectBoardLayoutIntegrity,
  formatLayoutIntegrityError,
  assertBoardLayoutIntegrity,
} from "./boardIntegrity.js";
